FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements-dev.txt /app/requirements-dev.txt

RUN pip install --upgrade pip
RUN pip install --no-deps --require-hashes --no-cache-dir --disable-pip-version-check -r /app/requirements-dev.txt

RUN pip install pip-tools

COPY . /app/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
